### ISSUE TITLE
broken installation from pypi

### ISSUE THREAD

**Issue by mazzma12** [benjaminpillot/gis-tools#1]
Hi there, just to mention that your installation from pypi is broken :/ 

``` 
Complete output (5 lines):                                                       
 Traceback (most recent call last):                                               
   File "<string>", line 1, in <module>                                           
   File "/tmp/pip-install-q03i0fmh/gis-tools/setup.py", line 8, in <module>       
     with open("requirements.txt") as req:                                        
 FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'       
 ----------------------------------------                                         
```

**Comment by benjaminpillot** [comment]
I've fixed the problem. Sorry for the inconvenience. Tell me if you encounter any new issue.
